Description:  Build VPC/Subnet/RouteTable/EIP/NAT

Parameters:
  VPC1CIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.1.0.0/16
  VPC1NATSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.1.1.0/24
  VPC1NATSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.1.2.0/24
  VPC1ApplianceSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.1.101.0/24
  VPC1ApplianceSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.1.102.0/24
  VPC1PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.1.201.0/24
  VPC1PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.1.202.0/24

Resources:
  # VPC and IGW
  VPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPC1CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: GWLB-VPC
  VPC1InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: GWLB-VPC
  VPC1InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: VPC1InternetGateway
    Properties:
      InternetGatewayId: !Ref VPC1InternetGateway
      VpcId: !Ref VPC1
  # EIP For NAT
  VPC1EIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: GWLB-VPC-AZ1-NAT
  VPC1EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: GWLB-VPC-AZ2-NAT

  # 6 subnets
  VPC1NATSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC1
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref VPC1NATSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: GWLB-VPC-NATSubnet1
  VPC1NATSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC1
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref VPC1NATSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: GWLB-VPC-NATSubnet2
  VPC1ApplianceSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC1
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref VPC1ApplianceSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: GWLB-VPC-ApplianceSubnet1
  VPC1ApplianceSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC1
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref VPC1ApplianceSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: GWLB-VPC-ApplianceSubnet2
  VPC1PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC1
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref VPC1PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: GWLB-VPC-PrivateSubnet1
  VPC1PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC1
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref VPC1PrivateSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: GWLB-VPC-PrivateSubnet2  

  # NAT Gateway
  VPC1NATGateway1:
    DependsOn: VPC1NATSubnet1
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt VPC1EIP1.AllocationId
      SubnetId: !Ref VPC1NATSubnet1
      Tags:
        - Key: Name
          Value: GWLB-VPC-NAT1
  VPC1NATGateway2:
    DependsOn: VPC1NATSubnet2
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt VPC1EIP2.AllocationId
      SubnetId: !Ref VPC1NATSubnet2
      Tags:
        - Key: Name
          Value: GWLB-VPC-NAT2

  # NATSubnet Routetable
  # AZ1
  VPC1NATSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: GWLB-VPC-NATSubnet1
  VPC1NATSubnet1Route:
    Type: AWS::EC2::Route
    DependsOn: VPC1InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref VPC1NATSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref VPC1InternetGateway
  VPC1NATSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VPC1NATSubnet1RouteTable
      SubnetId: !Ref VPC1NATSubnet1
  # AZ2
  VPC1NATSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: GWLB-VPC-NATSubnet2
  VPC1NATSubnet2Route:
    Type: AWS::EC2::Route
    DependsOn: VPC1InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref VPC1NATSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref VPC1InternetGateway
  VPC1NATSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VPC1NATSubnet2RouteTable
      SubnetId: !Ref VPC1NATSubnet2

  # ApplianceSubnet Routetable
  # AZ1 
  VPC1ApplianceSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: GWLB-VPC-ApplianceSubnet1
  VPC1ApplianceSubnet1Route:
    Type: AWS::EC2::Route
    DependsOn: VPC1NATGateway1
    Properties:
      RouteTableId: !Ref VPC1ApplianceSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref VPC1NATGateway1
  VPC1ApplianceSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VPC1ApplianceSubnet1RouteTable
      SubnetId: !Ref VPC1ApplianceSubnet1
  # AZ2
  VPC1ApplianceSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: GWLB-VPC-ApplianceSubnet2
  VPC1ApplianceSubnet2Route:
    Type: AWS::EC2::Route
    DependsOn: VPC1NATGateway2
    Properties:
      RouteTableId: !Ref VPC1ApplianceSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref VPC1NATGateway2
  VPC1ApplianceSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VPC1ApplianceSubnet2RouteTable
      SubnetId: !Ref VPC1ApplianceSubnet2

  # PrivateSubnet Route table
  # AZ1 
  VPC1PrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: GWLB-VPC-PrivateSubnet1
  VPC1PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VPC1PrivateSubnet1RouteTable
      SubnetId: !Ref VPC1PrivateSubnet1
  # AZ2
  VPC1PrivateSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC1
      Tags:
        - Key: Name
          Value: GWLB-VPC-PrivateSubnet2
  VPC1PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref VPC1PrivateSubnet2RouteTable
      SubnetId: !Ref VPC1PrivateSubnet2

Outputs:
    VPC1:
      Value: !Ref VPC1
    # Subnet ID
    VPC1NATSubnet1:
      Value: !Ref VPC1NATSubnet1
    VPC1NATSubnet2:
      Value: !Ref VPC1NATSubnet2
    VPC1ApplianceSubnet1:
      Value: !Ref VPC1ApplianceSubnet1
    VPC1ApplianceSubnet2:
      Value: !Ref VPC1ApplianceSubnet2
    VPC1PrivateSubnet1:
      Value: !Ref VPC1PrivateSubnet1
    VPC1PrivateSubnet2:
      Value: !Ref VPC1PrivateSubnet2
    # Route Table ID
    VPC1NATSubnet1RouteTable:
      Value: !Ref VPC1NATSubnet1RouteTable
    VPC1NATSubnet2RouteTable:
      Value: !Ref VPC1NATSubnet2RouteTable
    VPC1ApplianceSubnet1RouteTable:
      Value: !Ref VPC1ApplianceSubnet1RouteTable
    VPC1ApplianceSubnet2RouteTable:
      Value: !Ref VPC1ApplianceSubnet2RouteTable
    VPC1PrivateSubnet1RouteTable:
      Value: !Ref VPC1PrivateSubnet1RouteTable
    VPC1PrivateSubnet2RouteTable:
      Value: !Ref VPC1PrivateSubnet2RouteTable